### PR TITLE
Do not rewrite subnamespaces or classes containing "Zend" or "ZF"

### LINKED ISSUE #53: Tool should not rename classes using "Zend" or "ZF" in them
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0+

#### Summary

Given a class name such as `Some\Vendor\Zend\Form\ZendFormFactory`, the bridge rewrites this to `Some\Vendor\Zend\Form\LaminasFormFactory`. This can be problematic for 3rd party libraries and/or generated code.

#### Current behavior

Rewrites `Some\Vendor\Zend\Form\ZendFormFactory` to `Some\Vendor\Zend\Form\LaminasFormFactory`

#### How to reproduce

```php
$replacements = new Laminas\ZendFrameworkBridge\Replacements();
echo $replacements->replace(Some\Vendor\Zend\Form\ZendFormFactory::class);
```

#### Expected behavior

"Some\Vendor\Zend\Form\ZendFormFactory"

### PR DESCRIPTION
**Pull request by weierophinney**
This patch does the following:

- It changes the "edge-case" replacement maps (generally `[a-z]\\(Zend|ZF)\\`) to remove the trailing namespace separator. This allows them to match either subnamespaces _or_ classes.

- Adds additional rules for classes we specifically define within the framework that _should_ be replaced. These include:

  - `ZendAcl` from zend-expressive-authorization-acl
  - `ZendRbac` from zend-expressive-authorization-rbac
  - `ZendRouter` from zend-expressive-zendrouter
  - `ZendViewRenderer` from zend-expressive-zendviewrenderer

  In each case, I define:

  - the shortest possible match (class name without namespace)
  - ~the class name with the immediate parent namespace~ (Note: removed this, as it was a greedy lookup)
  - the fully qualified class name

  (The latter ~two variants have~ variant has two versions, to account for escaping the namespace separator.)

I've also added more test cases to verify that:

- Subnamespaces and user-defined classes do NOT get rewritten.
- Various known imports and definitions from our own packages get rewritten correctly.

Fixes #53

### CODE REVIEW

File: config/replacements.php [hunk 1]
```diff
@@ -151,112 +151,138 @@
...
+    'r\\Zend' => 'r\\Zend',
+    's\\Zend' => 's\\Zend',
+    't\\Zend' => 't\\Zend',
+    'u\\Zend' => 'u\\Zend',
+    'v\\Zend' => 'v\\Zend',
+    'w\\Zend' => 'w\\Zend',
+    'x\\Zend' => 'x\\Zend',
+    'y\\Zend' => 'y\\Zend',
+    'z\\Zend' => 'z\\Zend',
+    'a\\ZendOAuth' => 'a\\ZendOAuth',
```
Comment (michalbundyra) [inline config/replacements.php]: All these from `a\\ZendOAuth` to `z\\ZendXml` are redundant now, as we have just [a-z]\\Zend without trailing namespace separator

File: config/replacements.php [hunk 2]
```diff
@@ -151,112 +151,138 @@
...
-    'u\\ZendXml\\' => 'u\\ZendXml\\',
-    'v\\ZendXml\\' => 'v\\ZendXml\\',
-    'w\\ZendXml\\' => 'w\\ZendXml\\',
-    'x\\ZendXml\\' => 'x\\ZendXml\\',
-    'y\\ZendXml\\' => 'y\\ZendXml\\',
-    'z\\ZendXml\\' => 'z\\ZendXml\\',
+    // class ZendAcl in zend-expressive-authorization-acl
+    'ZendAcl' => 'LaminasAcl',
+    'Acl\\ZendAcl' => 'Acl\\LaminasAcl',
+    'Acl\\\\ZendAcl' => 'Acl\\\\LaminasAcl',
```
Comment (michalbundyra) [inline config/replacements.php]: Why do we need double namespace separator?

File: config/replacements.php [hunk 3]
```diff
@@ -151,112 +151,138 @@
...
-    't\\ZendXml\\' => 't\\ZendXml\\',
-    'u\\ZendXml\\' => 'u\\ZendXml\\',
-    'v\\ZendXml\\' => 'v\\ZendXml\\',
-    'w\\ZendXml\\' => 'w\\ZendXml\\',
-    'x\\ZendXml\\' => 'x\\ZendXml\\',
-    'y\\ZendXml\\' => 'y\\ZendXml\\',
-    'z\\ZendXml\\' => 'z\\ZendXml\\',
+    // class ZendAcl in zend-expressive-authorization-acl
+    'ZendAcl' => 'LaminasAcl',
+    'Acl\\ZendAcl' => 'Acl\\LaminasAcl',
```
Comment (michalbundyra) [inline config/replacements.php]: Do we have test case:
```php
'factories' => [
    'any-alias' => \Some\Vendor\Acl\ZendAcl::class,
],
```
?

**Review by michalbundyra — CHANGES_REQUESTED** [review]

File: config/replacements.php (hunk 2 above)
Comment (weierophinney) [reply config/replacements.php]: Probably overkill, but was doing it to mimic the namespace entries. But you're right - for this, not needed.

File: config/replacements.php (hunk 3 above)
Comment (weierophinney) [reply config/replacements.php]: I'll add one.

Comment (weierophinney) [reply config/replacements.php]: Fails. And that puts us in a strange area, because we really cannot control _every_ possible context.

I think we can only do:

- Bare name (e.g., `ZendAcl` becomes `LaminasAcl`)
- FCQN (e.g., `Zend\Expressive\Authorization\Acl\ZendAcl` becomes `Mezzio\Authorization\Acl\LaminasAcl`)

If we do the parent namespace as well, we start running into issues with other libraries too quickly.

I've just tried that approach (removing the version with the parent subnamespace), and all tests pass, including the new one you suggested, so I'm going to consider that a win. I'll push shortly.

Comment (michalbundyra) [reply config/replacements.php]: And in that case migration will fail on something like that:

```php
use Zend\Expressive\Authorization\Acl;

Acl\ZendAcl::class;
```

it will be migrated to:

```php
use Mezzio\Authorization\Acl;

Acl\ZendAcl::class; // <!-- wrong, should be Acl\LaminasAcl::class;
```

we should be aware of it - maybe add it into FAQ of the migration?

File: config/replacements.php (hunk 1 above)
Comment (weierophinney) [reply config/replacements.php]: Looks like length of key _does_ kick in here with regards to `strtr()` (based on 3v4l that @michalbundyra created): https://3v4l.org/dipMb

Comment (michalbundyra) [reply config/replacements.php]: Yes, but in that case it does not matter - as we do not want to have replaced these phrases, so still I believe we can remove all others and keep just `[a-z]\\Zend`

File: config/replacements.php (hunk 3 above)
Comment (michalbundyra) [reply config/replacements.php]: Also another case:
```php
use Some\Vendor\ZendAcl;

ZendAcl::class;
```

after migration it becomes:

```php
use Some\Vendor\ZendAcl;

LaminasAcl::class; // <-- wrong as this class does not exist, it should be ZendAcl::class
```

As in the previous comment, probably we cannot cover all cases so we should only add it into FAQ or Migration notes/issues.

More important is that PostProcessor replaces classes correctly and I believe we have achieved it here.

Comment (weierophinney) [reply config/replacements.php]: Agreed - these will need to be part of the FAQ.

I don't think they'll happen often, but they _can_ happen. I added test cases, and verified that they fail, and then removed them, as we expect those failures currently.

Comment (michalbundyra) [reply config/replacements.php]: @weierophinney created issue for that: https://github.com/laminas/laminas.github.io/issues/63

File: config/replacements.php [hunk 4]
```diff
@@ -151,112 +151,52 @@
...
-    'u\\ZendXml\\' => 'u\\ZendXml\\',
-    'v\\ZendXml\\' => 'v\\ZendXml\\',
-    'w\\ZendXml\\' => 'w\\ZendXml\\',
-    'x\\ZendXml\\' => 'x\\ZendXml\\',
-    'y\\ZendXml\\' => 'y\\ZendXml\\',
-    'z\\ZendXml\\' => 'z\\ZendXml\\',
+    // class ZendAcl in zend-expressive-authorization-acl
+    'ZendAcl' => 'LaminasAcl',
+    'Zend\\Expressive\\Authorization\\Acl\\ZendAcl' => 'Mezzio\\Authorization\\Acl\\LaminasAcl',
+    'Zend\\\\Expressive\\\\Authorization\\\\Acl\\\\ZendAcl' => 'Mezzio\\\\Authorization\\\\Acl\\\\LaminasAcl',
```
Comment (michalbundyra) [inline config/replacements.php]: Do we need this with duplicated namespace separators?

The same for couple more below.

Comment (weierophinney) [reply config/replacements.php]: Yes, because they could be in code as string values, and users often escape those (same reason we do double-escaped variants of namespaces above).

**Review by michalbundyra — APPROVED** [review]

File: config/replacements.php (hunk 4 above)
Comment (michalbundyra) [reply config/replacements.php]: There is another suggestion:
What if we keep just "single" namespace separator in that file and in https://github.com/laminas/laminas-zendframework-bridge/blob/master/src/Replacements.php
we add additional with double and quadruple namespace separators?

The file here will be much cleaner and it will solve also the other problem: 
https://github.com/laminas/laminas-migration/issues/26

I am fine with addressing it separately.

Comment (weierophinney) [reply config/replacements.php]: I've just pushed a commit with this change.

**Review by michalbundyra — APPROVED** [review]
🚢
