### PR TITLE
Bugfix regarding unaliased services

### LINKED ISSUE #51: `ConfigPostProcessor` replaces dependency service and therefore removes factory mapping
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

#### Summary

Hey guys, I am experiencing an issue with mezzio-only projects where the `ConfigPostProcessor` provided from this project replaces keys and values in the project configuration and by doing that, destroying the factory mapping for a zendframework service.

I've tried this with an mvc application but it seems that there are no such config replacements (because I could not reproduce this in there)?

#### Current behavior

The `ConfigPostProcessor` changes the factory mapping for the servicemanager as follows:

RAW configuration:
```php
[
    'factories' => [
        'Zend\Form\Factory' => 'SomeZendFormFactoryFactory',
    ],
]
```

Post processed configuration:
```php
[
    'factories' => [
        'Laminas\Form\Factory' => 'SomeZendFormFactoryFactory',
    ],
]
```

Now, the non-migrated module wants to retrieve the service from the servicemanager.
The servicemanager searches for the factory for `Zend\Form\Factory` as provided, but the post processed configuration does not know the `Zend\Form\Factory` factory anymore.

#### How to reproduce

I've created two repositories to provide an example on how the bug occurs:

Project (would be enough to check this out):
https://github.com/boesing/mezzio-project

Module which is not yet migrated to laminas:
https://github.com/boesing/zend-form-module

Run `composer serve` in the `mezzio-project` project and call `http://localhost:8080`. The error will occur.

#### Expected behavior

The proper laminas service should be instantiated. However, as this is a mapping issue for the service manager, I am not sure if this can be solved that easy. I guess there should be a dedicated replacement for all service- and pluginmanager configurations to solve that issue. Or probably you guys have another idea.

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

This is a fix for the related issue #51 

This change will add several, missing, aliases to the configuration after the post processor was executed. This will provide aliases for non-migrated packages which might be still required in an already migrated package.

### CODE REVIEW

**Review by weierophinney — APPROVED** [review]
:ship:

File: src/ConfigPostProcessor.php [hunk 1]
```diff
@@ -260,4 +278,35 @@ private function noopReplacement($value)
     {
         return $value;
     }
+
+    private function replaceDependencyFactories(array $config)
+    {
+        $factories = isset($config['factories']) ? $config['factories'] : [];
+        $aliases = isset($config['aliases']) ? $config['aliases'] : [];
```
Comment (michalbundyra) [inline src/ConfigPostProcessor.php]: we don't need these variables, in the loop we can just do:

```php
if (!isset($config['aliases'][$service'])) {
    $config['aliases'][$service'] = $replacedService;
}
```

and then we can also remove after the loop:

```php
       if ($aliases !== []) {
             $config['aliases'] = $aliases;
         }
```

the same with `$factories`.

It should reduce complexity and additional variables here.

**Comment by michalbundyra** [comment]
Thanks, @boesing!
