### PR TITLE
fix: migrate psr7bridge method calls

### LINKED ISSUE #27: Migrate psr7bridge message conversion methods
Usage methods `toZend()` and `fromZend()` from [psr7bridge](https://github.com/laminas/laminas-psr7bridge/blob/master/src/Psr7Response.php#L99-L113) calls didn't migrated to `toLaminas`/`fromLaminas`.

Old methods still works (they are deprecated) however will be nice if will be done right way.

### PR DESCRIPTION
**Pull request by weierophinney**
While we provided proxy methods for the original methods in the psr7bridge, when users migrate, they want their own calls to those methods to be migrated as well.

Fixes laminas/laminas-migration#27

### CODE REVIEW

File: config/replacements.php [hunk 1]
```diff
@@ -435,6 +435,8 @@
 
     // CONFIG KEYS, SCRIPT NAMES, ETC
     // ZF components
+    '::fromZend' => 'fromLaminas', // psr7bridge
+    '::toZend' => 'toLaminas', // psr7bridge
```
Comment (michalbundyra) [inline config/replacements.php]: missing `::` with rewrite pairs

**Review by michalbundyra — CHANGES_REQUESTED** [review]
@weierophinney Replace pairs are wrong. See comment below.

**Review by michalbundyra — APPROVED** [review]
🚢
